name: 'Setup Mage Action'
description: 'Downloads and installs the Mage tool'
branding:
  icon: sliders
  color: purple
inputs:
  version:
    required: true
    description: 'Version of Mage to install'
runs:
  using: 'node16'
  main: 'src/index.js'
